<div class="wrapper">
    <?php $this->loadComponent('navbar'); ?>
    <?php $this->loadComponent('sidebar'); ?>

    <div class="content-wrapper">
        <?php 
            $content = isset($_GET['content']) ? "content/".$_GET['content'] : "default";
            $this->loadComponent($content);
            
            if(empty($_SESSION['perfil'])){
                var_dump($_SESSION);
                $_SESSION['perfil'] = "avatar.png";
            }
        ?>
    </div>

    <?php $this->loadComponent('footer'); ?>
</div>