<!DOCTYPE html>
<html lang="pt-br">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Controle de Vendas</title>

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
	<link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
	<link rel="stylesheet" href="/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
	<link rel="shortcut icon" href="#" type="image/x-icon">
	<link rel="stylesheet" href="/dist/css/teste.css">
	<link rel="stylesheet" href="/dist/css/modalConfigs.css">
	<link rel="stylesheet" href="/dist/css/print.css" media="print">
	<script src="/plugins/jquery/jquery.min.js"></script>
</head>

<body class="hold-transition login-page">

	<?php $this->content() ?>

</body>
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

</html>