<body class="hold-transition login-page">
    <div class="login-box">
        <!-- /.login-logo -->
        <div class="card card-outline card-primary">
            <div class="card-header text-center">
                <a href="/" class="h1">Estoque</a>
            </div>
            <div class="card-body">
                <p class="login-box-msg">Insira seus dados para iniciar Sessão</p>

                <form action="/sessao" method="post">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="username" placeholder="Nome">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-user"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" name="password" placeholder="Senha">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block">Entrar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

</html>
<?php
if (isset($_GET['alert'])) {
    if ($_GET['alert'] == 1) {
        $this->view->type = 'danger';
        $this->view->msg = 'Usuario não encontrado Ou Inativo';
    } else if ($_GET['alert'] == 2) {
        $this->view->type = 'danger';
        $this->view->msg = 'Usuario e/ou Senha incorreta';
    }
    $this->view->time = '1 second ago';
    $this->view->page = 'produtos';
    $this->loadComponent('toast');
    echo '<script>delToast()</script>';
}
?>